# Generated by Django 4.0.4 on 2022-05-27 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Overwatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('num_damage', models.IntegerField(default=0, verbose_name='Damage Dealt')),
                ('num_blocked', models.IntegerField(default=0, verbose_name='Damage Blocked')),
                ('num_healed', models.IntegerField(default=0, verbose_name='Healing Done')),
                ('num_kills', models.IntegerField(default=0, verbose_name='Number of Kills')),
                ('num_assists', models.IntegerField(default=0, verbose_name='Number of Assists')),
                ('num_deaths', models.IntegerField(default=0, verbose_name='Number of Deaths')),
                ('objective_time', models.IntegerField(default=0, verbose_name='Objective Time (seconds)')),
                ('got_potg', models.BooleanField(default=False, verbose_name='Got POTG?')),
                ('got_card', models.BooleanField(default=False, verbose_name='Got a Card?')),
                ('did_win', models.BooleanField(verbose_name='Did you win?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
