# Generated by Django 3.2.13 on 2022-06-07 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RocketLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0, verbose_name='End Game Score')),
                ('got_mvp', models.BooleanField(default=False, verbose_name='Got MVP?')),
                ('did_win', models.BooleanField(default=False, verbose_name='Did you win?')),
                ('level', models.IntegerField(choices=[(0, 'wood'), (1, 'bronze'), (2, 'silver'), (3, 'gold'), (4, 'platinum'), (5, 'diamond'), (6, 'master')], default=3, verbose_name='Level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
